version: "3.2"

services:
  db:
    image: mysql
    container_name: network-mapping-db
    restart: always
    environment:
      MYSQL_DATABASE: 'network-mapping'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - network-mapping-db:/var/lib/mysql

volumes:
  network-mapping-db:
    driver: local